### PR TITLE
avoid re/create htpasswd if exists

### LINKED ISSUE #11: htpasswd file is droping it's manually modififed content
https://github.com/opscode-cookbooks/subversion/blob/master/recipes/server.rb#L49

"htpasswd -scb" -> remove "-c" it recreate htpasswd each time it runs, so manually added users are removed :-|.

### PR DESCRIPTION
**Pull request by epcim**
fixes #11 - by creating htpasswd only first time

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by epcim** [comment]
Hi, I already signed ti ICLA and even CCLA (epcim). If that is the issue 
keep my account under CCLA. Or is it actually required to let "github 
organizations" in this case apealive-cookbooks to sign CCLA independently?

Thanks, PMi

**Comment by sean-horn** [comment]
Hi, are your email addresses for both orgs the same? We think it should only be the author on the commits that matters to the bot.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @pmichalec

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tas50** [comment]
This same issue is fixed on master I believe. If I'm incorrect there feel free to rebase this and open it back up again, but I'm going to close it out now.

**Comment by iennae** [comment]
Thanks for the contribution @epcim. Apologies for the delay in pulling it in. I've gone ahead and rebased in #22.

**Pull request closed without merging**
